#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

TARGET=${1:-dev}
IMAGE="ghcr.io/angellusmortis/ark-operator-dev:latest"
if [[ "$TARGET" == "prod" ]]; then
    IMAGE="ghcr.io/angellusmortis/ark-operator:latest"
fi

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

pushd "$ROOT_PATH" 2>&1 >/dev/null

echo "Building $IMAGE..."
docker buildx build . -f Dockerfile --target $TARGET --tag $IMAGE

popd 2>&1 >/dev/null
